const fs = require('fs');
const path = require('path');

const content = `'use strict';
function getState() { if (typeof window !== 'undefined' && window.SidebarState) return window.SidebarState; if (typeof require !== 'undefined') return require('./state'); throw new Error('State module not available'); }
function getUtils() { if (typeof window !== 'undefined' && window.SidebarUtils) return window.SidebarUtils; if (typeof require !== 'undefined') return require('./utils'); throw new Error('Utils module not available'); }
function getAccountList() { if (typeof document !== 'undefined') return document.getElementById('account-list'); return null; }
function getEmptyState() { if (typeof document !== 'undefined') return document.getElementById('empty-state'); return null; }
function renderStatusDot(a, d) { if (!d || !a) return; d.className = 'status-dot'; if (a.status === 'online') d.classList.add('online'); else if (a.status === 'loading') d.classList.add('loading'); else if (a.status === 'error') d.classList.add('error'); else if (a.loginStatus === false || a.hasQRCode) { d.classList.add('warning'); d.title = '需要登录'; } else d.classList.add('offline'); }
function renderQuickActions(a, c) { if (!c || !a) return; c.innerHTML = ''; const rs = a.runningStatus || 'not_started'; const ir = !!a.isRunning; const b = document.createElement('button'); b.className = 'action-btn'; if (rs === 'error') { b.innerHTML = '↻'; b.classList.add('retry'); c.appendChild(b); } else if (rs === 'loading') { const s = document.createElement('div'); s.className = 'mini-spinner'; c.appendChild(s); } else if (rs === 'connected' || ir) { b.innerHTML = '⏹'; b.classList.add('stop'); c.appendChild(b); } else { b.innerHTML = '▶'; b.classList.add('start'); c.appendChild(b); } }
function renderUnreadBadge(a, c) { if (!a || !c) return; let b = c.querySelector('.unread-badge'); const n = parseInt(a.unreadCount || 0, 10); if (n > 0) { if (!b) { b = document.createElement('div'); b.className = 'unread-badge'; c.appendChild(b); } b.textContent = n > 99 ? '99+' : n; b.style.display = 'flex'; } else if (b) b.style.display = 'none'; }
function applyAccountProfileToItem(a, i) { if (!a || !i) return; const u = getUtils(); const n = a.profileName || a.name || ''; const ne = i.querySelector('.account-name'); if (ne) ne.textContent = n; const se = i.querySelector('.account-secondary'); if (se) { let pe = se.querySelector('.account-phone'); if (pe) { if (a.phoneNumber) { pe.textContent = a.phoneNumber; pe.style.display = ''; } else pe.style.display = 'none'; } } }
function createAccountItem(a, o = {}) { const s = getState(); const u = getUtils(); const i = document.createElement('div'); i.className = 'account-item'; if (a.loginStatus === true) i.classList.add('loggedin'); i.dataset.accountId = a.id; if (a.id === s.getActiveAccountId()) i.classList.add('active'); if (s.isSelectionMode()) { i.classList.add('in-selection-mode'); const cb = document.createElement('input'); cb.type = 'checkbox'; cb.className = 'selection-checkbox'; cb.checked = s.getSelectedAccountIds().has(a.id); i.appendChild(cb); if (s.getSelectedAccountIds().has(a.id)) i.classList.add('selected'); } const ac = document.createElement('div'); ac.className = 'account-avatar-container'; const av = document.createElement('div'); av.className = 'account-avatar'; if (a.name || a.profileName) { av.textContent = u.getAccountInitial(a.name || a.profileName); av.style.background = u.getAccountColor(a.id); } const sd = document.createElement('div'); sd.className = 'status-dot'; renderStatusDot(a, sd); ac.appendChild(av); ac.appendChild(sd); renderUnreadBadge(a, ac); const inf = document.createElement('div'); inf.className = 'account-info'; const h = document.createElement('div'); h.className = 'account-header'; const nm = document.createElement('div'); nm.className = 'account-name'; nm.textContent = a.name || ''; h.appendChild(nm); const sec = document.createElement('div'); sec.className = 'account-secondary'; const ph = document.createElement('div'); ph.className = 'account-phone'; if (a.phoneNumber) ph.textContent = a.phoneNumber; else ph.style.display = 'none'; sec.appendChild(ph); inf.appendChild(h); inf.appendChild(sec); const cn = document.createElement('div'); cn.className = 'account-collapsed-name'; cn.textContent = a.note || a.profileName || a.name || ''; inf.appendChild(cn); const act = document.createElement('div'); act.className = 'account-actions'; renderQuickActions(a, act); i.appendChild(ac); i.appendChild(inf); i.appendChild(act); applyAccountProfileToItem(a, i); return i; }
async function renderAccountList() { const al = getAccountList(); if (!al) return; const s = getState(); al.querySelectorAll('.account-item').forEach(i => i.remove()); const f = document.createDocumentFragment(); s.getAccounts().forEach(a => f.appendChild(createAccountItem(a))); al.appendChild(f); }
function updateAccountStatus(id, st) { const s = getState(); const a = s.getAccountById(id); if (!a) return; s.updateAccount(id, { status: st }); const al = getAccountList(); if (!al) return; const i = al.querySelector('[data-account-id="' + id + '"]'); if (!i) return; const d = i.querySelector('.status-dot'); if (d) renderStatusDot(a, d); }
function updateAccountRunningStatus(id, rs) { const s = getState(); const a = s.getAccountById(id); if (!a) return; s.updateAccount(id, { runningStatus: rs, isRunning: rs !== 'not_started' && rs !== 'error' }); const al = getAccountList(); if (!al) return; const i = al.querySelector('[data-account-id="' + id + '"]'); if (!i) return; const ac = i.querySelector('.account-actions'); if (ac) renderQuickActions(a, ac); }
function setActiveAccount(id) { const s = getState(); s.setActiveAccountId(id); const al = getAccountList(); if (!al) return; al.querySelectorAll('.account-item').forEach(i => { if (i.dataset.accountId === id) i.classList.add('active'); else i.classList.remove('active'); }); }
function updateSelectionUI() { const al = getAccountList(); if (!al) return; const s = getState(); s.getAccounts().forEach(a => { const i = al.querySelector('[data-account-id="' + a.id + '"]'); if (!i) return; i.classList.toggle('selected', s.getSelectedAccountIds().has(a.id)); }); }
const renderExports = { renderAccountList, createAccountItem, renderStatusDot, renderQuickActions, renderUnreadBadge, applyAccountProfileToItem, updateAccountStatus, updateAccountRunningStatus, setActiveAccount, updateSelectionUI, getAccountList, getEmptyState };
if (typeof module !== 'undefined' && module.exports) module.exports = renderExports;
if (typeof window !== 'undefined') window.SidebarRender = renderExports;
`;

const targetPath = path.join(__dirname, '..', 'src', 'single-window', 'renderer', 'sidebar', 'render.js');
fs.writeFileSync(targetPath, content, 'utf8');
console.log('Written to:', targetPath);
console.log('Size:', fs.statSync(targetPath).size);
